# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iPassSdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iPassSdk
    pod 'PKHUD', '~> 5.3'
    pod 'Alamofire', '~> 5.5'

  target 'iPassSdkTests' do
    # Pods for testing
  end

end
